import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createSyntaxCssBundle, createSyntaxJsBundle } from './lib/syntax-bundle.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });

const [css, js] = await Promise.all([
  createSyntaxCssBundle({ root }),
  createSyntaxJsBundle({ root }),
]);

await writeFile(path.join(dist, 'syntax.css'), css);
await writeFile(path.join(dist, 'syntax.js'), js);
await writeFile(
  path.join(dist, 'README.md'),
  '# Syntax distribution\n\nUse `syntax.css` and `syntax.js` in production. These files are generated by `npm run build`.\n',
);

console.log(`Built ${path.relative(root, dist)}/syntax.css and syntax.js`);
